# Generated by Django 5.1.4 on 2025-05-15 10:54

import cloudinary.models
import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0004_alter_projectimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('project_title', models.CharField(max_length=100)),
                ('project_cover', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('stack', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=15)),
                ('github_client', models.CharField(max_length=250)),
                ('github_server', models.CharField(max_length=250)),
                ('github_preview', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontend', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=15)),
                ('backend', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=10)),
                ('database', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=5)),
                ('devOps', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=10)),
                ('Others', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='name',
        ),
        migrations.AddField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='my_portfolio.project'),
            preserve_default=False,
        ),
    ]
