# Generated by Django 5.1.4 on 2025-05-20 12:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0008_alter_project_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='stack',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=list, null=True, size=15),
        ),
    ]
