# Generated by Django 5.1.4 on 2025-05-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0010_alter_project_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='display_project',
            field=models.BooleanField(default=False),
        ),
    ]
