# Generated by Django 5.1.4 on 2025-05-21 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0011_project_display_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='github_preview',
            new_name='project_preview',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
